### PR TITLE
Remove usage of simplejson

### PR DESCRIPTION
**Pull request by aehlke**
Suppresses warnings (noise in Sentry / logs).

Cherry-picked this from upstream. We still have a few uses of simplejson but only inside the test suite (of tastypie) which we don't currently run. Once this merges, will open a PR in our THM repo to run our test suite against a new internal release of tastypie to make sure our suite passes with these changes.

### CODE REVIEW

**Comment by aehlke** [comment]
We should run test suites of forked 3rd party libs to validate changes before making an internal release, but that's tech debt that's out of scope for me right now... What we can reasonably validate instead is that our THM test suite passes when electing to use the new internal release.

**Comment by aehlke** [comment]
Here's the warning this resolves:

>/home/vagrant/venv/app_tophat/local/lib/python2.7/site-packages/tastypie/serializers.py:7: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
>  from django.utils import simplejson

**Comment by YazIAm** [comment]
@aehlke would it be a lot more work to run the library's test suite?

otherwise LGTM

**Comment by aehlke** [comment]
@YazIAm I played around with it but the suite of the version we've forked off of has decayed too much. It seems to break with our version of Django (the requirements.txt simply requires `>=1.0`, lol) as well as the latest. Which is precarious - seems the things that break are features of tastypie that we don't use.

**Comment by aehlke** [comment]
I tried installing the oldest version pip lets me, Django 1.1.0, and it still fails for unrelated reasons.

**Pull request merged**
